version: '3.6'
services:
  hping:
    build:
      context: ./hping
      dockerfile: Dockerfile
    command: tail -F anything
    networks:
      - servers

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8080:80"
    networks:
      - servers

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    networks:
      - servers

  telegraf:
    image: telegraf:1.18-alpine
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./logs/telegraf/telegraf.log:/var/log/telegraf/telegraf.log
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmpx:/var/run/utmp:ro
    privileged: true
    user: root
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '127.0.0.1:8125:8125/udp'
    networks:
      - servers

  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - servers

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - servers

volumes:
  influxdb_data: {}
  grafana_data: {}

networks:
  servers:
    driver: bridge
