version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./media_volume:/home/app/web/project/media
    expose:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - APP_FOLDER=/home/app/web

  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8080:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    tmpfs:
      - /var/tmp/cache
    depends_on:
      - web
